--------------------------------------------------------
--  File created - Saturday-April-22-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_ALUMNOS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_ALUMNOS" 
   (	"CODIGO_ALUMNO" NUMBER(*,0), 
	"NUMERO_CUENTA" VARCHAR2(11 BYTE), 
	"PROMEDIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_AREA_ESPECIALIZACIONES
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_AREA_ESPECIALIZACIONES" 
   (	"CODIGO_ESPECIALIZACION" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_AREAS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_AREAS" 
   (	"CODIGO_AREA" NUMBER(*,0), 
	"NOMBRE_AREA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_ASIGNATURAS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_ASIGNATURAS" 
   (	"CODIGO_ASIGNATURA" NUMBER(*,0), 
	"CODIGO_ALTERNO" VARCHAR2(200 BYTE), 
	"NOMBRE_ASIGNATURA" VARCHAR2(4000 BYTE), 
	"CANTIDAD_UNIDADES_VALORATIVAS" NUMBER(*,0), 
	"DIAS" VARCHAR2(200 BYTE), 
	"CODIGO_CARRERA" NUMBER(*,0), 
	"CODIGO_TIPO_ASIGNATURA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_AULAS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_AULAS" 
   (	"CODIGO_AULA" NUMBER(*,0), 
	"NUMERO_AULA" VARCHAR2(100 BYTE), 
	"CODIGO_TIPO_AULA" NUMBER(*,0), 
	"CODIGO_EDIFICIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CAMPUS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_CAMPUS" 
   (	"CODIGO_CAMPUS" NUMBER(*,0), 
	"NOMBRE_CAMPUS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CARGOS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_CARGOS" 
   (	"CODIGO_CARGO" NUMBER(*,0), 
	"CODIGO_CARGO_SUPERIOR" NUMBER(*,0), 
	"NOMBRE_CARGO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CARRERAS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_CARRERAS" 
   (	"CODIGO_CARRERA" NUMBER(*,0), 
	"CODIGO_AUXILIAR" VARCHAR2(20 BYTE), 
	"CODIGO_FACULTAD" NUMBER(*,0), 
	"NOMBRE_CARRERA" VARCHAR2(200 BYTE), 
	"CANTIDAD_ASIGNATURAS" NUMBER(*,0), 
	"CANTIDAD_UNIDADES_VALORATIVAS" NUMBER(*,0), 
	"CODIGO_GRADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CARRERAS_X_ALUMNOS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_CARRERAS_X_ALUMNOS" 
   (	"CODIGO_CARRERA" NUMBER(*,0), 
	"CODIGO_ALUMNO" NUMBER(*,0), 
	"FECHA_REGISTRO_CARRERA" DATE, 
	"PROMEDIO_CARRERA" NUMBER, 
	"CANTIDAD_CLASES_APROBADAS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DETALLE_EVALUACION
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_DETALLE_EVALUACION" 
   (	"CODIGO_HISTORIAL" NUMBER(*,0), 
	"CODIGO_TIPO_EVALUACION" NUMBER(*,0), 
	"VALOR_NOTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_EDIFICIOS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_EDIFICIOS" 
   (	"CODIGO_EDIFICIO" NUMBER(*,0), 
	"NOMBRE_EDIFICIO" VARCHAR2(200 BYTE), 
	"ALIAS_EDIFICIO" VARCHAR2(200 BYTE), 
	"CODIGO_CAMPUS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_EMPLEADOS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_EMPLEADOS" 
   (	"CODIGO_EMPLEADO" NUMBER(*,0), 
	"NUMERO_EMPLEADO" NUMBER(*,0), 
	"SUELDO_BASE" NUMBER, 
	"CODIGO_TIPO_EMPLEADO" NUMBER(*,0), 
	"CODIGO_CARGO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_ESTADOS_CIVILES
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_ESTADOS_CIVILES" 
   (	"CODIGO_ESTADO_CIVIL" NUMBER(*,0), 
	"NOMBRE_ESTADO_CIVIL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_ESTADOS_MATRICULA
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_ESTADOS_MATRICULA" 
   (	"CODIGO_ESTADO_MATRICULA" NUMBER(*,0), 
	"NOMBRE_ESTADO" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_FACULTADES
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_FACULTADES" 
   (	"CODIGO_FACULTAD" NUMBER(*,0), 
	"NOMBRE_FACULTAD" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_GENEROS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_GENEROS" 
   (	"CODIGO_GENERO" NUMBER(*,0), 
	"NOMBRE_GENERO" VARCHAR2(60 BYTE), 
	"ABREVIATURA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_UNAH"."TBL_GENEROS"."CODIGO_GENERO" IS 'IDENTIFICADOR UNICO PARA EL CAMPO GENERO';
--------------------------------------------------------
--  DDL for Table TBL_GRADOS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_GRADOS" 
   (	"CODIGO_GRADO" NUMBER(*,0), 
	"NOMBRE_GRADO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_HISTORIAL
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_HISTORIAL" 
   (	"CODIGO_HISTORIAL" NUMBER(*,0), 
	"CODIGO_ALUMNO" NUMBER(*,0), 
	"CODIGO_SECCION" NUMBER(*,0), 
	"CODIGO_PERIODO" NUMBER(*,0), 
	"PROMEDIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_LUGARES
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_LUGARES" 
   (	"CODIGO_LUGAR" NUMBER(*,0), 
	"NOMBRE_LUGAR" VARCHAR2(200 BYTE), 
	"LONGITUD" NUMBER, 
	"LATITUD" NUMBER, 
	"CODIGO_TIPO_LUGAR" NUMBER(*,0), 
	"CODIGO_LUGAR_PADRE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_MAESTROS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_MAESTROS" 
   (	"CODIGO_MAESTRO" NUMBER(*,0), 
	"CODIGO_ESPECIALIZACION" NUMBER(*,0), 
	"CODIGO_TITULARIDAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_MATRICULA
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_MATRICULA" 
   (	"FECHA_MATRICULA" DATE, 
	"CODIGO_SECCION" NUMBER(*,0), 
	"CODIGO_ALUMNO" NUMBER(*,0), 
	"CODIGO_ESTADO_MATRICULA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PERIODOS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_PERIODOS" 
   (	"CODIGO_PERIODO" NUMBER(*,0), 
	"NOMBRE_PERIODO" VARCHAR2(200 BYTE), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE, 
	"CODIGO_TIPO_PERIODO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PERSONAS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_PERSONAS" 
   (	"CODIGO_PERSONA" NUMBER(*,0), 
	"CODIGO_GENERO" NUMBER(*,0), 
	"CODIGO_LUGAR_NACIMIENTO" NUMBER(*,0), 
	"CODIGO_LUGAR_RESIDENCIA" NUMBER(*,0), 
	"CODIGO_MUNICIPIO_NACIMIENTO" NUMBER(*,0), 
	"CODIGO_MUNICIPIO_RESIDENCIA" NUMBER(*,0), 
	"CODIGO_CAMPUS" NUMBER(*,0), 
	"CODIGO_TIPO_IDENTIFICACION" NUMBER(*,0), 
	"CODIGO_ESTADO_CIVIL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"APELLIDO" VARCHAR2(200 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"IDENTIDAD" VARCHAR2(13 BYTE), 
	"DIRECCION" VARCHAR2(800 BYTE), 
	"TELEFONO" VARCHAR2(30 BYTE), 
	"CORREO_ELECTRONICO" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_REQUISITOS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_REQUISITOS" 
   (	"CODIGO_ASIGNATURA" NUMBER(*,0), 
	"CODIGO_ASIGNATURA_REQUISITO" NUMBER(*,0), 
	"CODIGO_CARRERA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_SECCION
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_SECCION" 
   (	"CODIGO_SECCION" NUMBER(*,0), 
	"CODIGO_ALTERNO" VARCHAR2(200 BYTE), 
	"HORA_INICIO" DATE, 
	"HORA_FIN" DATE, 
	"DIAS" VARCHAR2(200 BYTE), 
	"CODIGO_AULA" NUMBER(*,0), 
	"CODIGO_ASIGNATURA" NUMBER(*,0), 
	"CODIGO_MAESTRO" NUMBER(*,0), 
	"CODIGO_PERIODO" NUMBER(*,0), 
	"CANTIDAD_CUPOS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_ASIGNATURA
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_TIPO_ASIGNATURA" 
   (	"CODIGO_TIPO_ASIGNATURA" NUMBER(*,0), 
	"TIPO_ASIGNATURA" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_EMPLEADO
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_TIPO_EMPLEADO" 
   (	"CODIGO_TIPO_EMPLEADO" NUMBER(*,0), 
	"NOMBRE_TIPO_EMPLEADO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_IDENTIFICACION
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_TIPO_IDENTIFICACION" 
   (	"CODIGO_TIPO_IDENTIFICACION" NUMBER(*,0), 
	"TIPO_IDENTIFICACION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_LUGARES
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_TIPO_LUGARES" 
   (	"CODIGO_TIPO_LUGAR" NUMBER(*,0), 
	"NOMBRE_TIPO_LUGAR" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPOS_AULAS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_TIPOS_AULAS" 
   (	"CODIGO_TIPO_AULA" NUMBER(*,0), 
	"TIPO_AULA" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPOS_EVALUACIONES
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_TIPOS_EVALUACIONES" 
   (	"CODIGO_TIPO_EVALUACION" NUMBER(*,0), 
	"NOMBRE_TIPO_EVALUACION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPOS_PERIODOS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_TIPOS_PERIODOS" 
   (	"CODIGO_TIPO_PERIODO" NUMBER(*,0), 
	"TIPO_PERIODO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_UNAH"."TBL_TIPOS_PERIODOS"."CODIGO_TIPO_PERIODO" IS 'Campo que identifica de forma unica un tipo de periodo';
--------------------------------------------------------
--  DDL for Table TBL_TITULARIDAD
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_TITULARIDAD" 
   (	"CODIGO_TITULARIDAD" NUMBER(*,0), 
	"NOMBRE_TITULARIDAD" VARCHAR2(200 BYTE), 
	"SALARIO_MINIMO" NUMBER, 
	"SALARIO_MAXIMO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TITULOS
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_TITULOS" 
   (	"CODIGO_TITULO" NUMBER(*,0), 
	"NOMBRE_TITULO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TITULOS_X_EMPLEADO
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_TITULOS_X_EMPLEADO" 
   (	"CODIGO_TITULO" NUMBER(*,0), 
	"CODIGO_EMPLEADO" NUMBER(*,0), 
	"CODIGO_UNIVERSIDAD" NUMBER(*,0), 
	"FECHA" DATE, 
	"NUMERO_REGISTRO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_UNIVERSIDADES
--------------------------------------------------------

  CREATE TABLE "DB_UNAH"."TBL_UNIVERSIDADES" 
   (	"CODIGO_UNIVERSIDAD" NUMBER(*,0), 
	"NOMBRE_UNIVERSIDAD" VARCHAR2(200 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_ALUMNOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_ALUMNOS_PK" ON "DB_UNAH"."TBL_ALUMNOS" ("CODIGO_ALUMNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_AREA_ESPECIALIZACIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_AREA_ESPECIALIZACIONES_PK" ON "DB_UNAH"."TBL_AREA_ESPECIALIZACIONES" ("CODIGO_ESPECIALIZACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_AREAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_AREAS_PK" ON "DB_UNAH"."TBL_AREAS" ("CODIGO_AREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_ASIGNATURAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_ASIGNATURAS_PK" ON "DB_UNAH"."TBL_ASIGNATURAS" ("CODIGO_ASIGNATURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_AULAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_AULAS_PK" ON "DB_UNAH"."TBL_AULAS" ("CODIGO_AULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CAMPUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_CAMPUS_PK" ON "DB_UNAH"."TBL_CAMPUS" ("CODIGO_CAMPUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CARGOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_CARGOS_PK" ON "DB_UNAH"."TBL_CARGOS" ("CODIGO_CARGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CARRERAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_CARRERAS_PK" ON "DB_UNAH"."TBL_CARRERAS" ("CODIGO_CARRERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CARRERAS_X_ALUMNOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_CARRERAS_X_ALUMNOS_PK" ON "DB_UNAH"."TBL_CARRERAS_X_ALUMNOS" ("CODIGO_CARRERA", "CODIGO_ALUMNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_EDIFICIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_EDIFICIOS_PK" ON "DB_UNAH"."TBL_EDIFICIOS" ("CODIGO_EDIFICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_EMPLEADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_EMPLEADOS_PK" ON "DB_UNAH"."TBL_EMPLEADOS" ("CODIGO_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_ESTADOS_CIVILES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_ESTADOS_CIVILES_PK" ON "DB_UNAH"."TBL_ESTADOS_CIVILES" ("CODIGO_ESTADO_CIVIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_ESTADOS_MATRICULA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_ESTADOS_MATRICULA_PK" ON "DB_UNAH"."TBL_ESTADOS_MATRICULA" ("CODIGO_ESTADO_MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_FACULTADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_FACULTADES_PK" ON "DB_UNAH"."TBL_FACULTADES" ("CODIGO_FACULTAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_GENEROS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_GENEROS_PK" ON "DB_UNAH"."TBL_GENEROS" ("CODIGO_GENERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_GRADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_GRADOS_PK" ON "DB_UNAH"."TBL_GRADOS" ("CODIGO_GRADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_HISTORIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_HISTORIAL_PK" ON "DB_UNAH"."TBL_HISTORIAL" ("CODIGO_HISTORIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_LUGARES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_LUGARES_PK" ON "DB_UNAH"."TBL_LUGARES" ("CODIGO_LUGAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_MAESTROS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_MAESTROS_PK" ON "DB_UNAH"."TBL_MAESTROS" ("CODIGO_MAESTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PERIODOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_PERIODOS_PK" ON "DB_UNAH"."TBL_PERIODOS" ("CODIGO_PERIODO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PERSONAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_PERSONAS_PK" ON "DB_UNAH"."TBL_PERSONAS" ("CODIGO_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_REQUISITOS__IDX
--------------------------------------------------------

  CREATE INDEX "DB_UNAH"."TBL_REQUISITOS__IDX" ON "DB_UNAH"."TBL_REQUISITOS" ("CODIGO_ASIGNATURA", "CODIGO_ASIGNATURA_REQUISITO", "CODIGO_CARRERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SECCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_SECCION_PK" ON "DB_UNAH"."TBL_SECCION" ("CODIGO_SECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPO_ASIGNATURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_TIPO_ASIGNATURA_PK" ON "DB_UNAH"."TBL_TIPO_ASIGNATURA" ("CODIGO_TIPO_ASIGNATURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPO_EMPLEADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_TIPO_EMPLEADO_PK" ON "DB_UNAH"."TBL_TIPO_EMPLEADO" ("CODIGO_TIPO_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPO_IDENTIFICACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_TIPO_IDENTIFICACION_PK" ON "DB_UNAH"."TBL_TIPO_IDENTIFICACION" ("CODIGO_TIPO_IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPO_LUGAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_TIPO_LUGAR_PK" ON "DB_UNAH"."TBL_TIPO_LUGARES" ("CODIGO_TIPO_LUGAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPOS_AULAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_TIPOS_AULAS_PK" ON "DB_UNAH"."TBL_TIPOS_AULAS" ("CODIGO_TIPO_AULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPOS_EVALUACIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_TIPOS_EVALUACIONES_PK" ON "DB_UNAH"."TBL_TIPOS_EVALUACIONES" ("CODIGO_TIPO_EVALUACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPOS_PERIODOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_TIPOS_PERIODOS_PK" ON "DB_UNAH"."TBL_TIPOS_PERIODOS" ("CODIGO_TIPO_PERIODO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TITULARIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_TITULARIDAD_PK" ON "DB_UNAH"."TBL_TITULARIDAD" ("CODIGO_TITULARIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TITULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_TITULOS_PK" ON "DB_UNAH"."TBL_TITULOS" ("CODIGO_TITULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TITULOS_X_EMPLEADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_TITULOS_X_EMPLEADO_PK" ON "DB_UNAH"."TBL_TITULOS_X_EMPLEADO" ("CODIGO_TITULO", "CODIGO_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_UNIVERSIDADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_UNAH"."TBL_UNIVERSIDADES_PK" ON "DB_UNAH"."TBL_UNIVERSIDADES" ("CODIGO_UNIVERSIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_ALUMNOS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_ALUMNOS" ADD CONSTRAINT "TBL_ALUMNOS_PK" PRIMARY KEY ("CODIGO_ALUMNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_ALUMNOS" MODIFY ("NUMERO_CUENTA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_ALUMNOS" MODIFY ("CODIGO_ALUMNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_AREA_ESPECIALIZACIONES
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_AREA_ESPECIALIZACIONES" ADD CONSTRAINT "TBL_AREA_ESPECIALIZACIONES_PK" PRIMARY KEY ("CODIGO_ESPECIALIZACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_AREA_ESPECIALIZACIONES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_AREA_ESPECIALIZACIONES" MODIFY ("CODIGO_ESPECIALIZACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_AREAS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_AREAS" ADD CONSTRAINT "TBL_AREAS_PK" PRIMARY KEY ("CODIGO_AREA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_AREAS" MODIFY ("CODIGO_AREA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_ASIGNATURAS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_ASIGNATURAS" ADD CONSTRAINT "TBL_ASIGNATURAS_PK" PRIMARY KEY ("CODIGO_ASIGNATURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_ASIGNATURAS" MODIFY ("CODIGO_TIPO_ASIGNATURA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_ASIGNATURAS" MODIFY ("CODIGO_CARRERA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_ASIGNATURAS" MODIFY ("CODIGO_ASIGNATURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_AULAS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_AULAS" ADD CONSTRAINT "TBL_AULAS_PK" PRIMARY KEY ("CODIGO_AULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_AULAS" MODIFY ("CODIGO_EDIFICIO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_AULAS" MODIFY ("CODIGO_TIPO_AULA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_AULAS" MODIFY ("NUMERO_AULA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_AULAS" MODIFY ("CODIGO_AULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CAMPUS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_CAMPUS" ADD CONSTRAINT "TBL_CAMPUS_PK" PRIMARY KEY ("CODIGO_CAMPUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_CAMPUS" MODIFY ("NOMBRE_CAMPUS" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_CAMPUS" MODIFY ("CODIGO_CAMPUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CARGOS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_CARGOS" ADD CONSTRAINT "TBL_CARGOS_PK" PRIMARY KEY ("CODIGO_CARGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_CARGOS" MODIFY ("CODIGO_CARGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CARRERAS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_CARRERAS" ADD CONSTRAINT "TBL_CARRERAS_PK" PRIMARY KEY ("CODIGO_CARRERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_CARRERAS" MODIFY ("CODIGO_GRADO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_CARRERAS" MODIFY ("CANTIDAD_ASIGNATURAS" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_CARRERAS" MODIFY ("CODIGO_FACULTAD" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_CARRERAS" MODIFY ("CODIGO_AUXILIAR" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_CARRERAS" MODIFY ("CODIGO_CARRERA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CARRERAS_X_ALUMNOS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_CARRERAS_X_ALUMNOS" ADD CONSTRAINT "TBL_CARRERAS_X_ALUMNOS_PK" PRIMARY KEY ("CODIGO_CARRERA", "CODIGO_ALUMNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_CARRERAS_X_ALUMNOS" MODIFY ("FECHA_REGISTRO_CARRERA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_CARRERAS_X_ALUMNOS" MODIFY ("CODIGO_ALUMNO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_CARRERAS_X_ALUMNOS" MODIFY ("CODIGO_CARRERA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_DETALLE_EVALUACION
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_DETALLE_EVALUACION" MODIFY ("VALOR_NOTA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_DETALLE_EVALUACION" MODIFY ("CODIGO_TIPO_EVALUACION" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_DETALLE_EVALUACION" MODIFY ("CODIGO_HISTORIAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_EDIFICIOS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_EDIFICIOS" ADD CONSTRAINT "TBL_EDIFICIOS_PK" PRIMARY KEY ("CODIGO_EDIFICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_EDIFICIOS" MODIFY ("CODIGO_CAMPUS" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_EDIFICIOS" MODIFY ("CODIGO_EDIFICIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_EMPLEADOS" ADD CONSTRAINT "TBL_EMPLEADOS_PK" PRIMARY KEY ("CODIGO_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_EMPLEADOS" MODIFY ("CODIGO_CARGO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_EMPLEADOS" MODIFY ("CODIGO_TIPO_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_EMPLEADOS" MODIFY ("SUELDO_BASE" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_EMPLEADOS" MODIFY ("NUMERO_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_EMPLEADOS" MODIFY ("CODIGO_EMPLEADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_ESTADOS_CIVILES
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_ESTADOS_CIVILES" ADD CONSTRAINT "TBL_ESTADOS_CIVILES_PK" PRIMARY KEY ("CODIGO_ESTADO_CIVIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_ESTADOS_CIVILES" MODIFY ("NOMBRE_ESTADO_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_ESTADOS_CIVILES" MODIFY ("CODIGO_ESTADO_CIVIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_ESTADOS_MATRICULA
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_ESTADOS_MATRICULA" ADD CONSTRAINT "TBL_ESTADOS_MATRICULA_PK" PRIMARY KEY ("CODIGO_ESTADO_MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_ESTADOS_MATRICULA" MODIFY ("CODIGO_ESTADO_MATRICULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_FACULTADES
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_FACULTADES" ADD CONSTRAINT "TBL_FACULTADES_PK" PRIMARY KEY ("CODIGO_FACULTAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_FACULTADES" MODIFY ("CODIGO_FACULTAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_GENEROS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_GENEROS" ADD CONSTRAINT "TBL_GENEROS_PK" PRIMARY KEY ("CODIGO_GENERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_GENEROS" MODIFY ("NOMBRE_GENERO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_GENEROS" MODIFY ("CODIGO_GENERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_GRADOS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_GRADOS" ADD CONSTRAINT "TBL_GRADOS_PK" PRIMARY KEY ("CODIGO_GRADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_GRADOS" MODIFY ("NOMBRE_GRADO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_GRADOS" MODIFY ("CODIGO_GRADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_HISTORIAL
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_HISTORIAL" ADD CONSTRAINT "TBL_HISTORIAL_PK" PRIMARY KEY ("CODIGO_HISTORIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_HISTORIAL" MODIFY ("PROMEDIO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_HISTORIAL" MODIFY ("CODIGO_PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_HISTORIAL" MODIFY ("CODIGO_SECCION" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_HISTORIAL" MODIFY ("CODIGO_ALUMNO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_HISTORIAL" MODIFY ("CODIGO_HISTORIAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_LUGARES
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_LUGARES" ADD CONSTRAINT "TBL_LUGARES_PK" PRIMARY KEY ("CODIGO_LUGAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_LUGARES" MODIFY ("CODIGO_TIPO_LUGAR" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_LUGARES" MODIFY ("NOMBRE_LUGAR" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_LUGARES" MODIFY ("CODIGO_LUGAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_MAESTROS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_MAESTROS" ADD CONSTRAINT "TBL_MAESTROS_PK" PRIMARY KEY ("CODIGO_MAESTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_MAESTROS" MODIFY ("CODIGO_TITULARIDAD" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_MAESTROS" MODIFY ("CODIGO_ESPECIALIZACION" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_MAESTROS" MODIFY ("CODIGO_MAESTRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_MATRICULA
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_MATRICULA" MODIFY ("CODIGO_ESTADO_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_MATRICULA" MODIFY ("CODIGO_ALUMNO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_MATRICULA" MODIFY ("CODIGO_SECCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PERIODOS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_PERIODOS" ADD CONSTRAINT "TBL_PERIODOS_PK" PRIMARY KEY ("CODIGO_PERIODO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_PERIODOS" MODIFY ("CODIGO_TIPO_PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERIODOS" MODIFY ("CODIGO_PERIODO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PERSONAS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" ADD CONSTRAINT "TBL_PERSONAS_PK" PRIMARY KEY ("CODIGO_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("CORREO_ELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("IDENTIDAD" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("CODIGO_ESTADO_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("CODIGO_TIPO_IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("CODIGO_CAMPUS" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("CODIGO_MUNICIPIO_RESIDENCIA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("CODIGO_MUNICIPIO_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("CODIGO_LUGAR_RESIDENCIA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("CODIGO_LUGAR_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("CODIGO_GENERO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_PERSONAS" MODIFY ("CODIGO_PERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_REQUISITOS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_REQUISITOS" MODIFY ("CODIGO_CARRERA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_REQUISITOS" MODIFY ("CODIGO_ASIGNATURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_SECCION
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_SECCION" ADD CONSTRAINT "TBL_SECCION_PK" PRIMARY KEY ("CODIGO_SECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_SECCION" MODIFY ("CODIGO_PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_SECCION" MODIFY ("CODIGO_MAESTRO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_SECCION" MODIFY ("CODIGO_ASIGNATURA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_SECCION" MODIFY ("CODIGO_AULA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_SECCION" MODIFY ("CODIGO_ALTERNO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_SECCION" MODIFY ("CODIGO_SECCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_ASIGNATURA
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_TIPO_ASIGNATURA" ADD CONSTRAINT "TBL_TIPO_ASIGNATURA_PK" PRIMARY KEY ("CODIGO_TIPO_ASIGNATURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_TIPO_ASIGNATURA" MODIFY ("CODIGO_TIPO_ASIGNATURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_EMPLEADO
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_TIPO_EMPLEADO" ADD CONSTRAINT "TBL_TIPO_EMPLEADO_PK" PRIMARY KEY ("CODIGO_TIPO_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_TIPO_EMPLEADO" MODIFY ("CODIGO_TIPO_EMPLEADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_IDENTIFICACION
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_TIPO_IDENTIFICACION" ADD CONSTRAINT "TBL_TIPO_IDENTIFICACION_PK" PRIMARY KEY ("CODIGO_TIPO_IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_TIPO_IDENTIFICACION" MODIFY ("TIPO_IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_TIPO_IDENTIFICACION" MODIFY ("CODIGO_TIPO_IDENTIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_LUGARES
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_TIPO_LUGARES" ADD CONSTRAINT "TBL_TIPO_LUGAR_PK" PRIMARY KEY ("CODIGO_TIPO_LUGAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_TIPO_LUGARES" MODIFY ("NOMBRE_TIPO_LUGAR" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_TIPO_LUGARES" MODIFY ("CODIGO_TIPO_LUGAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPOS_AULAS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_TIPOS_AULAS" ADD CONSTRAINT "TBL_TIPOS_AULAS_PK" PRIMARY KEY ("CODIGO_TIPO_AULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_TIPOS_AULAS" MODIFY ("TIPO_AULA" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_TIPOS_AULAS" MODIFY ("CODIGO_TIPO_AULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPOS_EVALUACIONES
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_TIPOS_EVALUACIONES" ADD CONSTRAINT "TBL_TIPOS_EVALUACIONES_PK" PRIMARY KEY ("CODIGO_TIPO_EVALUACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_TIPOS_EVALUACIONES" MODIFY ("CODIGO_TIPO_EVALUACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPOS_PERIODOS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_TIPOS_PERIODOS" ADD CONSTRAINT "TBL_TIPOS_PERIODOS_PK" PRIMARY KEY ("CODIGO_TIPO_PERIODO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_TIPOS_PERIODOS" MODIFY ("CODIGO_TIPO_PERIODO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TITULARIDAD
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_TITULARIDAD" ADD CONSTRAINT "TBL_TITULARIDAD_PK" PRIMARY KEY ("CODIGO_TITULARIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_TITULARIDAD" MODIFY ("CODIGO_TITULARIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TITULOS
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_TITULOS" ADD CONSTRAINT "TBL_TITULOS_PK" PRIMARY KEY ("CODIGO_TITULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_TITULOS" MODIFY ("NOMBRE_TITULO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_TITULOS" MODIFY ("CODIGO_TITULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TITULOS_X_EMPLEADO
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_TITULOS_X_EMPLEADO" ADD CONSTRAINT "TBL_TITULOS_X_EMPLEADO_PK" PRIMARY KEY ("CODIGO_TITULO", "CODIGO_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_TITULOS_X_EMPLEADO" MODIFY ("CODIGO_UNIVERSIDAD" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_TITULOS_X_EMPLEADO" MODIFY ("CODIGO_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "DB_UNAH"."TBL_TITULOS_X_EMPLEADO" MODIFY ("CODIGO_TITULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_UNIVERSIDADES
--------------------------------------------------------

  ALTER TABLE "DB_UNAH"."TBL_UNIVERSIDADES" ADD CONSTRAINT "TBL_UNIVERSIDADES_PK" PRIMARY KEY ("CODIGO_UNIVERSIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_UNAH"."TBL_UNIVERSIDADES" MODIFY ("CODIGO_UNIVERSIDAD" NOT NULL ENABLE);
